# Generated by Django 3.0.5 on 2020-04-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pegasus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectId', models.CharField(max_length=200)),
                ('SvcNo', models.CharField(max_length=200)),
                ('SvcOrderStatus', models.CharField(max_length=200)),
                ('WorkOrder', models.CharField(max_length=200)),
                ('WorkOrderStatus', models.CharField(max_length=200)),
                ('CRD', models.DateField()),
                ('Speed', models.CharField(max_length=200)),
                ('Updates', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Pegasus Records',
            },
        ),
    ]
