# Generated by Django 3.0.5 on 2020-04-30 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SearchWo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pegasus',
            options={'managed': False, 'verbose_name_plural': 'Pegasus Records'},
        ),
    ]
