# Generated by Django 2.1.5 on 2020-04-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('projectid', models.CharField(max_length=200)),
                ('svcno', models.CharField(max_length=200)),
                ('svcorderstatus', models.CharField(max_length=200)),
                ('workorder', models.CharField(max_length=200)),
                ('workorderstatus', models.CharField(max_length=200)),
                ('crd', models.DateField()),
                ('speed', models.CharField(max_length=200)),
                ('updates', models.CharField(max_length=200)),
                ('Billed_status', models.CharField(max_length=200)),
                ('Billed_by', models.CharField(max_length=200)),
                ('Billed_date', models.DateField()),
            ],
            options={
                'managed': True,
            },
        ),
    ]
