# Generated by Django 3.0.5 on 2020-04-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mydb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectId', models.CharField(max_length=200)),
                ('WorkOrder', models.CharField(max_length=200)),
                ('CircuitId', models.CharField(max_length=200)),
                ('CrdDate', models.DateField()),
                ('Status', models.CharField(max_length=200)),
                ('Assignee', models.CharField(max_length=200)),
                ('AssignedTeam', models.CharField(max_length=200)),
            ],
        ),
    ]
