# Generated by Django 2.1.5 on 2020-04-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pol',
            fields=[
                ('projectid', models.TextField(blank=True, db_column='ProjectID', null=True)),
                ('projectcrd', models.DateField(blank=True, db_column='ProjectCRD', null=True)),
                ('projectstatus', models.TextField(blank=True, db_column='ProjectStatus', null=True)),
                ('team', models.TextField(blank=True, db_column='Team', null=True)),
                ('id', models.IntegerField(blank=True, db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'POL',
                'managed': True,
            },
        ),
    ]
